import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import '../../../../core/constants/app_colors.dart';
import '../../../../core/constants/app_sizes.dart';
import '../../../../core/constants/app_typography.dart';
import '../../../../core/extensions/theme_ext.dart';
import '../../../../core/widgets/app_button.dart';
import '../../../../core/widgets/app_card.dart';
import '../../domain/barcode_label_pdf_generator.dart';
import '../../domain/entities/product.dart';
import '../controllers/inventory_controller.dart';

/// Screen for selecting products and printing barcode labels as a PDF.
/// Uses the native OS print dialog via the `printing` package.
class PrintLabelsScreen extends ConsumerStatefulWidget {
  final String? preselectedProductId;
  const PrintLabelsScreen({super.key, this.preselectedProductId});

  @override
  ConsumerState<PrintLabelsScreen> createState() => _PrintLabelsScreenState();
}

class _PrintLabelsScreenState extends ConsumerState<PrintLabelsScreen> {
  final Map<String, int> _selected = {}; // productId -> copies
  bool _showOnlyAutoGenerated = true;

  @override
  void initState() {
    super.initState();
    if (widget.preselectedProductId != null) {
      _selected[widget.preselectedProductId!] = 1;
    }
  }

  @override
  Widget build(BuildContext context) {
    final productsAsync = ref.watch(productsProvider);

    return Scaffold(
      backgroundColor: context.appBackground,
      appBar: AppBar(
        title: const Text('Print Barcode Labels'),
        backgroundColor: context.appSurface,
        foregroundColor: context.appTextPrimary,
        elevation: 0,
      ),
      body: productsAsync.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (e, _) => Center(child: Text('Error loading products: $e')),
        data: (allProducts) {
          final products = _showOnlyAutoGenerated
              ? allProducts
                  .where((p) => p.sku.startsWith('INV-'))
                  .toList()
              : allProducts;

          return Column(
            children: [
              // Filter toggle
              Padding(
                padding: const EdgeInsets.all(AppSizes.screenPaddingH),
                child: Row(
                  children: [
                    Expanded(
                      child: Text(
                        'Auto-generated codes only',
                        style: AppTypography.bodyMedium.copyWith(
                          color: context.appTextPrimary,
                        ),
                      ),
                    ),
                    Switch(
                      value: _showOnlyAutoGenerated,
                      onChanged: (v) =>
                          setState(() => _showOnlyAutoGenerated = v),
                      activeThumbColor: AppColors.primary,
                    ),
                  ],
                ),
              ),
              // Product list
              Expanded(
                child: products.isEmpty
                    ? Center(
                        child: Text(
                          _showOnlyAutoGenerated
                              ? 'No auto-generated barcodes found.\nTurn off the filter to see all products.'
                              : 'No products found.',
                          textAlign: TextAlign.center,
                          style: AppTypography.bodyMedium.copyWith(
                            color: context.appTextSecondary,
                          ),
                        ),
                      )
                    : ListView.builder(
                        padding: const EdgeInsets.symmetric(
                            horizontal: AppSizes.screenPaddingH),
                        itemCount: products.length,
                        itemBuilder: (context, index) {
                          final product = products[index];
                          final isSelected =
                              _selected.containsKey(product.id);
                          final copies = _selected[product.id] ?? 1;

                          return Padding(
                            padding:
                                const EdgeInsets.only(bottom: AppSizes.sm),
                            child: AppCard(
                              child: Row(
                                children: [
                                  Checkbox(
                                    value: isSelected,
                                    activeColor: AppColors.primary,
                                    onChanged: (v) => setState(() {
                                      if (v == true) {
                                        _selected[product.id] = 1;
                                      } else {
                                        _selected.remove(product.id);
                                      }
                                    }),
                                  ),
                                  Expanded(
                                    child: Column(
                                      crossAxisAlignment:
                                          CrossAxisAlignment.start,
                                      children: [
                                        Text(product.name,
                                            style: AppTypography.bodyMedium
                                                .copyWith(
                                                    color: context
                                                        .appTextPrimary)),
                                        Text(
                                          product.barcode ?? product.sku,
                                          style: AppTypography.labelSmall
                                              .copyWith(
                                                  color: context
                                                      .appTextSecondary),
                                        ),
                                      ],
                                    ),
                                  ),
                                  if (isSelected) ...[
                                    IconButton(
                                      icon: const Icon(
                                          Icons
                                              .remove_circle_outline_rounded),
                                      color: AppColors.primary,
                                      onPressed: () => setState(() {
                                        if (copies > 1) {
                                          _selected[product.id] =
                                              copies - 1;
                                        }
                                      }),
                                    ),
                                    Text(
                                      '$copies',
                                      style: AppTypography.bodyMedium
                                          .copyWith(
                                              color:
                                                  context.appTextPrimary),
                                    ),
                                    IconButton(
                                      icon: const Icon(
                                          Icons.add_circle_outline_rounded),
                                      color: AppColors.primary,
                                      onPressed: () => setState(() =>
                                          _selected[product.id] =
                                              copies + 1),
                                    ),
                                  ],
                                ],
                              ),
                            ),
                          );
                        },
                      ),
              ),
              // Print button
              SafeArea(
                child: Padding(
                  padding: const EdgeInsets.all(AppSizes.screenPaddingH),
                  child: AppButton(
                    label: _selected.isEmpty
                        ? 'Select products to print'
                        : 'Print ${_selected.values.fold(0, (a, b) => a + b)} Label(s)',
                    onPressed: _selected.isEmpty
                        ? null
                        : () => _generateAndPrint(allProducts),
                  ),
                ),
              ),
            ],
          );
        },
      ),
    );
  }

  Future<void> _generateAndPrint(List<Product> products) async {
    final items = _selected.entries.map((e) {
      final product = products.firstWhere((p) => p.id == e.key);
      return LabelItem(product: product, copies: e.value);
    }).toList();

    final doc = await BarcodeLabelPdfGenerator.build(items);

    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
      name: 'inventra-barcode-labels',
    );
  }
}
